CREATE TABLE IF NOT EXISTS DER_CONTROLS (
    CONTROL_ID TEXT PRIMARY KEY NOT NULL,
    IS_DEFAULT INTEGER NOT NULL,
    CONTROL_TYPE TEXT NOT NULL,
    IS_SUPERSEDED INTEGER NOT NULL DEFAULT 0,
    PRIORITY INTEGER NOT NULL,
    START_TIME TEXT,
    DURATION REAL,
    CONTROL_JSON TEXT NOT NULL
);
